openapi: 3.0.3
info:
  title: News Api using DRF
  version: 1.0.0
  description: News Api, Brings the Latest News
paths:
  /hello/:
    get:
      operationId: hello_retrieve
      tags:
      - hello
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
