# Generated by Django 4.2.7 on 2023-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newskeepermodel',
            name='date',
            field=models.CharField(max_length=11),
        ),
    ]
